// server configuration

// server listen port
server_port=4444;

// scheduler mode: high, middle, low
scheduler_mode='low';

echo("server_port = " + server_port + "\n");
echo("scheduler_mode = " + scheduler_mode + "\n");
